# Generated by Django 5.0.6 on 2024-07-29 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="教学楼名称")),
                ("info", models.TextField(verbose_name="教学楼简介")),
                ("location", models.TextField(verbose_name="教学楼地址")),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="设备名")),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "空调"),
                            (2, "电脑"),
                            (3, "白板系统"),
                            (4, "音箱"),
                            (5, "实验仪器"),
                            (6, "其他"),
                        ],
                        verbose_name="设备类型",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="教室名称")),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "普通教室"),
                            (2, "艺术教室"),
                            (3, "研讨室"),
                            (4, "多媒体教室"),
                            (5, "实验室"),
                            (6, "其他"),
                        ],
                        verbose_name="教室类型",
                    ),
                ),
                ("size", models.IntegerField(verbose_name="容量")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "上课使用"), (2, "临时借用"), (3, "考试使用")],
                        verbose_name="状态",
                    ),
                ),
                ("add_info", models.TextField(verbose_name="备注")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.building",
                        verbose_name="所属教学楼",
                    ),
                ),
                (
                    "device_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.device",
                        verbose_name="设备",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserInfo",
        ),
    ]
