# Generated by Django 5.0.6 on 2024-07-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_building_device_room_delete_userinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="add_info",
            field=models.TextField(default="无", verbose_name="备注"),
        ),
    ]
