# Generated by Django 5.0.6 on 2024-07-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0004_device_add_info_alter_building_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "空闲"), (2, "上课使用"), (3, "临时借用"), (4, "考试使用")],
                verbose_name="状态",
            ),
        ),
    ]
