# Generated by Django 5.0.6 on 2024-07-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0006_alter_room_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="device_list",
            field=models.ManyToManyField(
                blank=True, to="app01.device", verbose_name="设备"
            ),
        ),
    ]
