# Generated by Django 5.0.6 on 2024-08-01 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0007_alter_room_device_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.SmallIntegerField(verbose_name="预约类型")),
                ("appoint_info", models.TextField(verbose_name="预约原因及用途")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "appoint_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.room",
                        verbose_name="预约教室",
                    ),
                ),
            ],
        ),
    ]
