# Generated by Django 5.0.6 on 2024-08-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0008_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="type",
        ),
        migrations.AddField(
            model_name="appointment",
            name="appoint_type",
            field=models.SmallIntegerField(
                choices=[(2, "上课使用"), (3, "临时借用"), (4, "考试使用")],
                null=True,
                verbose_name="预约类型",
            ),
        ),
    ]
