# Generated by Django 5.0.6 on 2024-08-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0009_remove_appointment_type_appointment_appoint_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appoint_info",
            field=models.CharField(max_length=100, verbose_name="预约原因及用途"),
        ),
    ]
